# Generated by Django 3.0.7 on 2020-07-11 20:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkiKulturowe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspire_id', models.CharField(max_length=50)),
                ('nazwa', models.CharField(max_length=255)),
                ('informacje', models.CharField(max_length=255)),
                ('kod_wojewo', models.CharField(max_length=2)),
                ('kod_powiat', models.CharField(max_length=4)),
                ('nadl', models.CharField(max_length=80)),
                ('rdlp', models.CharField(max_length=80)),
                ('uwagi', models.CharField(max_length=200)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
