# Generated by Django 3.1.1 on 2021-05-06 14:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkiKulturowe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspire_id', models.CharField(max_length=50)),
                ('nazwa', models.CharField(max_length=255)),
                ('informacje', models.CharField(max_length=255)),
                ('kod_województwa', models.CharField(max_length=2)),
                ('kod_powiatu', models.CharField(max_length=4)),
                ('jednostka', models.CharField(max_length=80)),
                ('RDLP_lub_zakład', models.CharField(max_length=80)),
                ('uwagi', models.CharField(max_length=200)),
                ('geometria', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': ' Parki kulturowe',
            },
        ),
        migrations.CreateModel(
            name='PomnikiHistorii',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspire_id', models.CharField(max_length=50)),
                ('nazwa', models.CharField(max_length=254)),
                ('rodzaj_pomnika', models.CharField(max_length=254)),
                ('dokładność_geometrii', models.CharField(max_length=254)),
                ('rodzaj_dokumentu', models.CharField(max_length=100)),
                ('data_utworzenia', models.CharField(max_length=10)),
                ('kod_województwa', models.CharField(max_length=2)),
                ('kod_powiatu', models.CharField(max_length=16)),
                ('jednostka', models.CharField(max_length=80)),
                ('RDLP_lub_zakład', models.CharField(max_length=80)),
                ('uwagi', models.CharField(max_length=200)),
                ('geometria', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': ' Pomniki historii',
            },
        ),
        migrations.CreateModel(
            name='UNESCO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspire_id', models.CharField(max_length=50)),
                ('nazwa', models.CharField(max_length=100)),
                ('rodzaj_dziedzictwa', models.CharField(max_length=254)),
                ('dokładność_geometrii', models.CharField(max_length=254)),
                ('rodzaj_dokumentu', models.CharField(max_length=100)),
                ('data_utworzenia', models.CharField(max_length=4)),
                ('kod_województwa', models.CharField(max_length=2)),
                ('kod_powiatu', models.CharField(max_length=16)),
                ('jednostka', models.CharField(max_length=80)),
                ('RDLP_lub_zakład', models.CharField(max_length=80)),
                ('geometria', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': ' Zabytki UNESCO',
            },
        ),
        migrations.CreateModel(
            name='ZabytkiRuchome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=254)),
                ('rodzaj_dokumentu', models.CharField(max_length=254)),
                ('jednostka', models.CharField(max_length=254)),
                ('RDLP_lub_zakład', models.CharField(max_length=254)),
                ('geometria', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': ' Zabytki ruchome',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('Jednostka', models.CharField(max_length=100, verbose_name='Jednostka')),
                ('RDLP_Zak', models.CharField(max_length=100, verbose_name='RDLP/Zakład krajowy')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
