# Generated by Django 3.1.1 on 2020-09-07 10:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zabytki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UNESCO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspire_id', models.CharField(max_length=50)),
                ('nazwa', models.CharField(max_length=100)),
                ('rodz_dzie', models.CharField(max_length=254)),
                ('dokl_geom', models.CharField(max_length=254)),
                ('rodzaj_dok', models.CharField(max_length=100)),
                ('dat_utw', models.CharField(max_length=4)),
                ('kod_woj', models.CharField(max_length=2)),
                ('kod_powiat', models.CharField(max_length=16)),
                ('nadl', models.CharField(max_length=80)),
                ('rdlp', models.CharField(max_length=80)),
                ('pol', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
