# Generated by Django 3.1.1 on 2020-09-07 15:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zabytki', '0002_unesco'),
    ]

    operations = [
        migrations.CreateModel(
            name='PomnikiHistorii',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspire_id', models.CharField(max_length=50)),
                ('nazwa', models.CharField(max_length=254)),
                ('rodz_ph', models.CharField(max_length=254)),
                ('dokl_geom', models.CharField(max_length=254)),
                ('rodzaj_dok', models.CharField(max_length=100)),
                ('dat_utw', models.CharField(max_length=10)),
                ('kod_woj', models.CharField(max_length=2)),
                ('kod_powiat', models.CharField(max_length=16)),
                ('nadl', models.CharField(max_length=80)),
                ('rdlp', models.CharField(max_length=80)),
                ('uwagi', models.CharField(max_length=200)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.RemoveField(
            model_name='unesco',
            name='pol',
        ),
    ]
