# Generated by Django 3.1.1 on 2020-09-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zabytki', '0006_auto_20200907_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkikulturowe',
            old_name='rdlp',
            new_name='RDLP',
        ),
        migrations.RenameField(
            model_name='parkikulturowe',
            old_name='geom',
            new_name='geometria',
        ),
        migrations.RenameField(
            model_name='parkikulturowe',
            old_name='kod_wojewodztwa',
            new_name='kod_województwa',
        ),
        migrations.RenameField(
            model_name='parkikulturowe',
            old_name='nadl',
            new_name='nadleśnictwo',
        ),
        migrations.RenameField(
            model_name='pomnikihistorii',
            old_name='rdlp',
            new_name='RDLP',
        ),
        migrations.RenameField(
            model_name='pomnikihistorii',
            old_name='dokladnosc_geometrii',
            new_name='dokładność_geometrii',
        ),
        migrations.RenameField(
            model_name='pomnikihistorii',
            old_name='kod_wojewodztwa',
            new_name='kod_województwa',
        ),
        migrations.RenameField(
            model_name='pomnikihistorii',
            old_name='nadlesnictwo',
            new_name='nadleśnictwo',
        ),
        migrations.RenameField(
            model_name='unesco',
            old_name='dokładnosc_geometrii',
            new_name='dokładność_geometrii',
        ),
        migrations.RenameField(
            model_name='zabytkiruchome',
            old_name='rdlp_lub_zaklad',
            new_name='RDLP_lub_Zakład',
        ),
    ]
