# Generated by Django 3.1.1 on 2020-09-07 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zabytki', '0007_auto_20200907_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zabytkiruchome',
            old_name='RDLP_lub_Zakład',
            new_name='RDLP_lub_zakład',
        ),
    ]
