# Generated by Django 3.1.1 on 2020-09-09 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zabytki', '0008_auto_20200907_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkikulturowe',
            options={'verbose_name_plural': ' Parki kulturowe'},
        ),
        migrations.AlterModelOptions(
            name='pomnikihistorii',
            options={'verbose_name_plural': ' Pomniki historii'},
        ),
        migrations.AlterModelOptions(
            name='unesco',
            options={'verbose_name_plural': ' Zabytki UNESCO'},
        ),
        migrations.AlterModelOptions(
            name='zabytkiruchome',
            options={'verbose_name_plural': ' Zabytki ruchome'},
        ),
    ]
